site_name: Zettlr Docs
site_url: https://docs.zettlr.com/en
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Our comprehensive documentation provides you with everything you need to
    know about how to make the most of Zettlr.
site_author: Hendrik Erz
copyright: "&copy; 2017-2020 by Zettlr"
docs_dir: ../docs/fr
site_dir: ../build/fr
edit_uri: edit/master/docs/fr
extra_css:
  - assets/app.css
nav:
  - Bonjour: index.md
  - Installation: install.md
  - Zettlr dans 5 minutes: 5-minutes.md
  - Guides:
    - Zettlr comme application de prise de notes: guides/guide-notes.md
    - Zettlr comme Zettelkasten: guides/guide-zettelkasten.md
    - Zettlr en tant qu'environnement de développement intégré (IDE): guides/guide-ide.md
  - Core:
    - L'éditeur: core/editor.md
    - La liste de fichiers: core/file-list.md
    - Recherche: core/search.md
    - Exporter dans Zettlr: core/export.md
    - Les tableaux dans Zettlr: core/tables.md
    - Répertoires virtuels: core/virtual-directories.md
    - CSS Personnalisés: core/custom-css.md
    - Localisation: core/localisation.md
    - L'encadré (sidebar) des pièces jointes: core/attachments.md
  - Academic Tools:
    - Citer avec Zettlr: academic/citations.md
    - Projets: academic/projects.md
    - Presentations: academic/presentations.md
    - Pomodoro Timer: academic/pomodoro.md
    - Lisibilité: academic/readability.md
    - La méthode Zettelkasten: academic/zkn-method.md
    - Modèles personnalisés: academic/custom-templates.md
  - References:
    - Raccourcis: reference/shortcuts.md
    - Bases Markdown: reference/markdown-basics.md
    - Paramétrage: reference/settings.md
    - Dictionnaires et vérification orthographique: reference/spell-checking.md
  - Get involved: get-involved.md
  - FAQ: faq.md
theme:
  name: readthedocs
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search:
      lang: fr
